import type { Metadata } from "next";
import "./globals.css";
import Header from "./_components/Header";
import Footer from "./_components/Footer";
import localFont from "next/font/local";

// const lackFont = localFont({
//   src: "../../public/lack-regular-webfont.woff",
//   variable: "--font-lack",
//   display: "swap",
// });

const lackFont = localFont({
  src: "../../public/lack-regular-webfont.woff",
  variable: "--font-lack",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lackFont.className}`}>
        <Header />

        <main>{children}</main>

        <Footer />
      </body>
    </html>
  );
}
